# Generated by Django 2.2 on 2020-04-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteDash_app', '0003_quote_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='like',
            new_name='user_likes',
        ),
    ]
