# Generated by Django 2.2 on 2020-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteDash_app', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_first_name', models.CharField(max_length=255)),
                ('new_last_name', models.CharField(max_length=255)),
                ('new_email', models.CharField(max_length=255)),
            ],
        ),
    ]
