# Generated by Django 2.2 on 2020-04-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteDash_app', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='like',
            field=models.ManyToManyField(related_name='liked_quote', to='quoteDash_app.User'),
        ),
    ]
