# Generated by Django 2.2 on 2020-04-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteDash_app', '0004_auto_20200425_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_email', models.CharField(max_length=255)),
                ('logged_password', models.CharField(max_length=255)),
            ],
        ),
    ]
